### ISSUE TITLE
Instructing maven-hpi-plugin to use pluginFirstClassLoader to load bundled Guava

### ISSUE THREAD

**Issue by TamalSaha** [appscode-ci/appscode-login-plugin#4]
Instruct maven-hpi-plugin to use pluginFirstClassLoader so login plugin will prefer the version of guava it bundles rather than the one core happens to use. Both shading and class masking had subtle problems.

- https://jenkinsci.github.io/maven-hpi-plugin/plugin-info.html 
- https://jenkinsci.github.io/maven-hpi-plugin/hpl-mojo.html#pluginFirstClassLoader 
- https://github.com/jenkinsci/openstack-cloud-plugin/blob/de02466d84f00eac7260345cc6784f354aabf76a/pom.xml#L117-L123 

**ref:**
https://groups.google.com/d/msg/jenkinsci-dev/SMMGhUMZnBM/Xi-D4VNjAAAJ

**Comment by TamalSaha** [comment]
https://github.com/appscode-ci/appscode-login-plugin/commit/a0b4af4efe85aea328d772e09358f27febe42f73

**Comment by TamalSaha** [comment]
`PFL` is not really wokring. Blue Ocean plugin also faces the `Iterables.skip()` MNF exception.

```
Jun 01 09:47:17 cim authbind[22007]: Jun 01, 2017 9:47:17 AM org.eclipse.jetty.util.log.JavaUtilLog warn
Jun 01 09:47:17 cim authbind[22007]: WARNING: Error for /blue/rest/search/
Jun 01 09:47:17 cim authbind[22007]: java.lang.NoSuchMethodError: com.google.common.collect.Iterators.skip(Ljava/util/Iterator;I)I
Jun 01 09:47:17 cim authbind[22007]: at io.jenkins.blueocean.rest.pageable.Pageables.slice(Pageables.java:35)
Jun 01 09:47:17 cim authbind[22007]: at io.jenkins.blueocean.rest.pageable.Pageables$1.iterator(Pageables.java:52)
Jun 01 09:47:17 cim authbind[22007]: at io.jenkins.blueocean.rest.pageable.PagedResponse$Processor$1.generateResponse(PagedResponse.java:57)
```

**Comment by TamalSaha** [comment]
cc: @sadlil @ashiquzzaman33

**Comment by TamalSaha** [comment]
```
[INFO] +- io.grpc:grpc-protobuf:jar:1.3.0:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.2.0:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- com.google.api.grpc:grpc-google-common-protos:jar:0.1.6:compile
[INFO] |  \- io.grpc:grpc-protobuf-lite:jar:1.3.0:compile
```
